#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_fogg_asg_instances="0.0.1"
  jq -n --arg fogg_asg_instances "$ver_fogg_asg_instances" '{fogg_asg_instances: $fogg_asg_instances}'
}

version "$@"
